INSERT INTO CATEGORY (DESCRIPTION) VALUES ('AMERICAN');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('ITALIAN');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('MEXICAN');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('FAST FOOD');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('TEASPOON');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('TABLESPOON');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('CUP');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('PINCH');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('OUNCE');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('EACH');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('DASH');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('PINT');

